apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: {{ .Values.odoo.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.odoo.name }}
    spec:
      containers:
        - name: {{ .Values.odoo.name }}
          image: "{{ .Values.odoo.image.registry }}/{{ .Values.odoo.image.repository }}:{{ .Values.odoo.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PGUSER
              value: "{{ .Values.postgres.postgresUser }}"
            - name: PGPASSWORD
              value: "{{ .Values.postgres.postgresPassword }}"
            - name: PGDATABASE
              value: "{{ .Values.postgres.postgresDatabase }}"
            - name: PGPORT
              value: "{{ .Values.postgres.service.port }}"
            - name: PGHOST
              value: "{{ .Values.postgres.postgresService }}"
          resources: {}
          #override the docker command to run odoo
          args: ["/usr/src/app/odoo-bin", "--addons-path=/usr/src/app/addons", "-i base", "--without-demo=all"]