apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: {{ .Values.odoo.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.odoo.name }}
    spec:
      containers:
        - name: {{ .Values.odoo.name }}
          #image: "{{ .Values.odoo.image.repository }}:{{ .Values.odoo.image.tag }}"
          image: "odoo-source:local"
          imagePullPolicy: Never
          ports:
          env:
            - name: USER
              value: "{{ .Values.postgres.postgresUser }}"
            - name: PASSWORD
              value: "{{ .Values.postgres.postgresPassword }}"
            - name: DB_NAME
              value: "{{ .Values.postgres.postgresDatabase }}"
            - name: PORT
              value: "{{ .Values.postgres.service.port }}"
            - name: HOST
              value: "{{ .Values.postgres.postgresService }}"
          resources: {}