apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.odoo.fullname }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.odoo.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.odoo.name }}
    spec:
      containers:
        - name: {{ .Values.odoo.name}}
          image: "odoo-custom:latest"
          ports:
            - containerPort: 8069
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgresDatabase  }}
          resources: {}

        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgresDatabase  }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
