apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odoo.fullname }}
spec:
  selector:
    app: {{ .Values.odoo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.odoo.service.port }}
      targetPort: {{ .Values.odoo.service.port }}
      nodePort: 30000  # Specify a desired node port
  type: NodePort
