apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odoo.fullname }}
spec:
  selector:
    app: {{ .Values.odoo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8069
  type: {{ .Values.service.type }}
