postgres:
  enabled: true
  image:
    repository: postgres
    tag: 13
  postgresUser: odoo
  postgresPassword: odoo
  postgresDatabase: odoo-main
  name: postgres
  service:
    port: 5432
    type: ClusterIP

odoo:
  image:
    repository: odoo
    tag: 16.0
  fullname: odoo-deployment
  name: odoo
  service:
    port: 8069
    type: ClusterIP
