postgres:
  enabled: true
  image:
    repository: localhost:32000/postgres-custom:local
  postgresUser: odoo
  postgresPassword: odoo
  postgresDatabase: odoo
  postgresService: postgres-service
  name: postgres
  service:
    port: 5432
    type: ClusterIP

odoo:
  image:
    repository: odoo-source
    tag: local
  fullname: odoo-deployment
  name: odoo
  service:
    port: 8069
    type: ClusterIP
